# Generated by Django 3.1.4 on 2020-12-16 04:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci_cli', models.CharField(max_length=10, unique=True, verbose_name='CI')),
                ('apellido_cli', models.CharField(max_length=30, verbose_name='Apellido')),
                ('nombre_cli', models.CharField(max_length=30, verbose_name='Nombre')),
                ('num_cell_cli', models.CharField(blank=True, max_length=9, null=True, verbose_name='Celular')),
                ('sexo_cli', models.CharField(choices=[('hombre', 'hombre'), ('mujer', 'mujer')], default='hombre', max_length=7, verbose_name='Sexo')),
                ('tipo_cli', models.CharField(choices=[('diario', 'Diario'), ('mensual', 'Mensual'), ('especial', 'Especial')], default='diario', max_length=9, verbose_name='Tipo cliente')),
                ('f_created', models.DateField(default=datetime.datetime(2020, 12, 15, 23, 11, 44, 737765), verbose_name='Registrado el')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Cliente',
                'db_table': 'cliente',
                'ordering': ['f_created'],
            },
        ),
    ]
