# Generated by Django 3.1.4 on 2020-12-16 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appCliente', '0002_auto_20201215_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_ini_pago', models.DateField()),
                ('f_exp_pago', models.DateField()),
                ('comentario_pago', models.CharField(blank=True, max_length=100, null=True)),
                ('fk_cli_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCliente.cliente', verbose_name='pago del cliente')),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'pagos',
                'db_table': 'pago',
                'ordering': ['id'],
            },
        ),
    ]
